#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoPlatformaOI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VideoPlatformaOI")]
	public partial class OIVideoPlatformaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDirektorVideo(DirektorVideo instance);
    partial void UpdateDirektorVideo(DirektorVideo instance);
    partial void DeleteDirektorVideo(DirektorVideo instance);
    partial void InsertPravnaVideo(PravnaVideo instance);
    partial void UpdatePravnaVideo(PravnaVideo instance);
    partial void DeletePravnaVideo(PravnaVideo instance);
    partial void InsertEkonomskaVideo(EkonomskaVideo instance);
    partial void UpdateEkonomskaVideo(EkonomskaVideo instance);
    partial void DeleteEkonomskaVideo(EkonomskaVideo instance);
    partial void InsertITVideo(ITVideo instance);
    partial void UpdateITVideo(ITVideo instance);
    partial void DeleteITVideo(ITVideo instance);
    partial void InsertKlijent(Klijent instance);
    partial void UpdateKlijent(Klijent instance);
    partial void DeleteKlijent(Klijent instance);
    partial void InsertKorisnik(Korisnik instance);
    partial void UpdateKorisnik(Korisnik instance);
    partial void DeleteKorisnik(Korisnik instance);
    #endregion
		
		public OIVideoPlatformaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VideoPlatformaOIConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OIVideoPlatformaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OIVideoPlatformaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OIVideoPlatformaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OIVideoPlatformaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DirektorVideo> DirektorVideos
		{
			get
			{
				return this.GetTable<DirektorVideo>();
			}
		}
		
		public System.Data.Linq.Table<PravnaVideo> PravnaVideos
		{
			get
			{
				return this.GetTable<PravnaVideo>();
			}
		}
		
		public System.Data.Linq.Table<EkonomskaVideo> EkonomskaVideos
		{
			get
			{
				return this.GetTable<EkonomskaVideo>();
			}
		}
		
		public System.Data.Linq.Table<ITVideo> ITVideos
		{
			get
			{
				return this.GetTable<ITVideo>();
			}
		}
		
		public System.Data.Linq.Table<Klijent> Klijents
		{
			get
			{
				return this.GetTable<Klijent>();
			}
		}
		
		public System.Data.Linq.Table<Korisnik> Korisniks
		{
			get
			{
				return this.GetTable<Korisnik>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DirektorVideo")]
	public partial class DirektorVideo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVidea;
		
		private string _Naslov;
		
		private string _Opis;
		
		private string _Video;
		
		private string _Datum;
		
		private string _Vrsta;
		
		private System.Nullable<int> _IdKorisnika;
		
		private EntityRef<Korisnik> _Korisnik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVideaChanging(int value);
    partial void OnIdVideaChanged();
    partial void OnNaslovChanging(string value);
    partial void OnNaslovChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnDatumChanging(string value);
    partial void OnDatumChanged();
    partial void OnVrstaChanging(string value);
    partial void OnVrstaChanged();
    partial void OnIdKorisnikaChanging(System.Nullable<int> value);
    partial void OnIdKorisnikaChanged();
    #endregion
		
		public DirektorVideo()
		{
			this._Korisnik = default(EntityRef<Korisnik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVidea", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVidea
		{
			get
			{
				return this._IdVidea;
			}
			set
			{
				if ((this._IdVidea != value))
				{
					this.OnIdVideaChanging(value);
					this.SendPropertyChanging();
					this._IdVidea = value;
					this.SendPropertyChanged("IdVidea");
					this.OnIdVideaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naslov", DbType="NVarChar(150)")]
		public string Naslov
		{
			get
			{
				return this._Naslov;
			}
			set
			{
				if ((this._Naslov != value))
				{
					this.OnNaslovChanging(value);
					this.SendPropertyChanging();
					this._Naslov = value;
					this.SendPropertyChanged("Naslov");
					this.OnNaslovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(500)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="NVarChar(150)")]
		public string Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="NVarChar(50)")]
		public string Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vrsta", DbType="NVarChar(50)")]
		public string Vrsta
		{
			get
			{
				return this._Vrsta;
			}
			set
			{
				if ((this._Vrsta != value))
				{
					this.OnVrstaChanging(value);
					this.SendPropertyChanging();
					this._Vrsta = value;
					this.SendPropertyChanged("Vrsta");
					this.OnVrstaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorisnika", DbType="Int")]
		public System.Nullable<int> IdKorisnika
		{
			get
			{
				return this._IdKorisnika;
			}
			set
			{
				if ((this._IdKorisnika != value))
				{
					if (this._Korisnik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._IdKorisnika = value;
					this.SendPropertyChanged("IdKorisnika");
					this.OnIdKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_DirektorVideo", Storage="_Korisnik", ThisKey="IdKorisnika", OtherKey="IdKorisnika", IsForeignKey=true)]
		public Korisnik Korisnik
		{
			get
			{
				return this._Korisnik.Entity;
			}
			set
			{
				Korisnik previousValue = this._Korisnik.Entity;
				if (((previousValue != value) 
							|| (this._Korisnik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Korisnik.Entity = null;
						previousValue.DirektorVideos.Remove(this);
					}
					this._Korisnik.Entity = value;
					if ((value != null))
					{
						value.DirektorVideos.Add(this);
						this._IdKorisnika = value.IdKorisnika;
					}
					else
					{
						this._IdKorisnika = default(Nullable<int>);
					}
					this.SendPropertyChanged("Korisnik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PravnaVideo")]
	public partial class PravnaVideo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVidea;
		
		private string _Naslov;
		
		private string _Opis;
		
		private string _Video;
		
		private string _Datum;
		
		private string _Vrsta;
		
		private System.Nullable<int> _IdKorisnika;
		
		private EntityRef<Korisnik> _Korisnik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVideaChanging(int value);
    partial void OnIdVideaChanged();
    partial void OnNaslovChanging(string value);
    partial void OnNaslovChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnDatumChanging(string value);
    partial void OnDatumChanged();
    partial void OnVrstaChanging(string value);
    partial void OnVrstaChanged();
    partial void OnIdKorisnikaChanging(System.Nullable<int> value);
    partial void OnIdKorisnikaChanged();
    #endregion
		
		public PravnaVideo()
		{
			this._Korisnik = default(EntityRef<Korisnik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVidea", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdVidea
		{
			get
			{
				return this._IdVidea;
			}
			set
			{
				if ((this._IdVidea != value))
				{
					this.OnIdVideaChanging(value);
					this.SendPropertyChanging();
					this._IdVidea = value;
					this.SendPropertyChanged("IdVidea");
					this.OnIdVideaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naslov", DbType="NVarChar(50)")]
		public string Naslov
		{
			get
			{
				return this._Naslov;
			}
			set
			{
				if ((this._Naslov != value))
				{
					this.OnNaslovChanging(value);
					this.SendPropertyChanging();
					this._Naslov = value;
					this.SendPropertyChanged("Naslov");
					this.OnNaslovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(500)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="NVarChar(50)")]
		public string Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="NVarChar(50)")]
		public string Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vrsta", DbType="NVarChar(50)")]
		public string Vrsta
		{
			get
			{
				return this._Vrsta;
			}
			set
			{
				if ((this._Vrsta != value))
				{
					this.OnVrstaChanging(value);
					this.SendPropertyChanging();
					this._Vrsta = value;
					this.SendPropertyChanged("Vrsta");
					this.OnVrstaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorisnika", DbType="Int")]
		public System.Nullable<int> IdKorisnika
		{
			get
			{
				return this._IdKorisnika;
			}
			set
			{
				if ((this._IdKorisnika != value))
				{
					if (this._Korisnik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._IdKorisnika = value;
					this.SendPropertyChanged("IdKorisnika");
					this.OnIdKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_PravnaVideo", Storage="_Korisnik", ThisKey="IdKorisnika", OtherKey="IdKorisnika", IsForeignKey=true)]
		public Korisnik Korisnik
		{
			get
			{
				return this._Korisnik.Entity;
			}
			set
			{
				Korisnik previousValue = this._Korisnik.Entity;
				if (((previousValue != value) 
							|| (this._Korisnik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Korisnik.Entity = null;
						previousValue.PravnaVideos.Remove(this);
					}
					this._Korisnik.Entity = value;
					if ((value != null))
					{
						value.PravnaVideos.Add(this);
						this._IdKorisnika = value.IdKorisnika;
					}
					else
					{
						this._IdKorisnika = default(Nullable<int>);
					}
					this.SendPropertyChanged("Korisnik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EkonomskaVideo")]
	public partial class EkonomskaVideo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVidea;
		
		private string _Naslov;
		
		private string _Opis;
		
		private string _Video;
		
		private string _Datum;
		
		private string _Vrsta;
		
		private System.Nullable<int> _IdKorisnika;
		
		private EntityRef<Korisnik> _Korisnik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVideaChanging(int value);
    partial void OnIdVideaChanged();
    partial void OnNaslovChanging(string value);
    partial void OnNaslovChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnDatumChanging(string value);
    partial void OnDatumChanged();
    partial void OnVrstaChanging(string value);
    partial void OnVrstaChanged();
    partial void OnIdKorisnikaChanging(System.Nullable<int> value);
    partial void OnIdKorisnikaChanged();
    #endregion
		
		public EkonomskaVideo()
		{
			this._Korisnik = default(EntityRef<Korisnik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVidea", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVidea
		{
			get
			{
				return this._IdVidea;
			}
			set
			{
				if ((this._IdVidea != value))
				{
					this.OnIdVideaChanging(value);
					this.SendPropertyChanging();
					this._IdVidea = value;
					this.SendPropertyChanged("IdVidea");
					this.OnIdVideaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naslov", DbType="NVarChar(100)")]
		public string Naslov
		{
			get
			{
				return this._Naslov;
			}
			set
			{
				if ((this._Naslov != value))
				{
					this.OnNaslovChanging(value);
					this.SendPropertyChanging();
					this._Naslov = value;
					this.SendPropertyChanged("Naslov");
					this.OnNaslovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(500)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="NVarChar(50)")]
		public string Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="NVarChar(50)")]
		public string Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vrsta", DbType="NVarChar(50)")]
		public string Vrsta
		{
			get
			{
				return this._Vrsta;
			}
			set
			{
				if ((this._Vrsta != value))
				{
					this.OnVrstaChanging(value);
					this.SendPropertyChanging();
					this._Vrsta = value;
					this.SendPropertyChanged("Vrsta");
					this.OnVrstaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorisnika", DbType="Int")]
		public System.Nullable<int> IdKorisnika
		{
			get
			{
				return this._IdKorisnika;
			}
			set
			{
				if ((this._IdKorisnika != value))
				{
					if (this._Korisnik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._IdKorisnika = value;
					this.SendPropertyChanged("IdKorisnika");
					this.OnIdKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_EkonomskaVideo", Storage="_Korisnik", ThisKey="IdKorisnika", OtherKey="IdKorisnika", IsForeignKey=true)]
		public Korisnik Korisnik
		{
			get
			{
				return this._Korisnik.Entity;
			}
			set
			{
				Korisnik previousValue = this._Korisnik.Entity;
				if (((previousValue != value) 
							|| (this._Korisnik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Korisnik.Entity = null;
						previousValue.EkonomskaVideos.Remove(this);
					}
					this._Korisnik.Entity = value;
					if ((value != null))
					{
						value.EkonomskaVideos.Add(this);
						this._IdKorisnika = value.IdKorisnika;
					}
					else
					{
						this._IdKorisnika = default(Nullable<int>);
					}
					this.SendPropertyChanged("Korisnik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ITVideo")]
	public partial class ITVideo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVidea;
		
		private string _Naslov;
		
		private string _Opis;
		
		private string _Video;
		
		private string _Datum;
		
		private string _Vrsta;
		
		private System.Nullable<int> _IdKorisnik;
		
		private EntityRef<Korisnik> _Korisnik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVideaChanging(int value);
    partial void OnIdVideaChanged();
    partial void OnNaslovChanging(string value);
    partial void OnNaslovChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnDatumChanging(string value);
    partial void OnDatumChanged();
    partial void OnVrstaChanging(string value);
    partial void OnVrstaChanged();
    partial void OnIdKorisnikChanging(System.Nullable<int> value);
    partial void OnIdKorisnikChanged();
    #endregion
		
		public ITVideo()
		{
			this._Korisnik = default(EntityRef<Korisnik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVidea", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVidea
		{
			get
			{
				return this._IdVidea;
			}
			set
			{
				if ((this._IdVidea != value))
				{
					this.OnIdVideaChanging(value);
					this.SendPropertyChanging();
					this._IdVidea = value;
					this.SendPropertyChanged("IdVidea");
					this.OnIdVideaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naslov", DbType="NVarChar(50)")]
		public string Naslov
		{
			get
			{
				return this._Naslov;
			}
			set
			{
				if ((this._Naslov != value))
				{
					this.OnNaslovChanging(value);
					this.SendPropertyChanging();
					this._Naslov = value;
					this.SendPropertyChanged("Naslov");
					this.OnNaslovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="NVarChar(500)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="NVarChar(500)")]
		public string Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="NVarChar(50)")]
		public string Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vrsta", DbType="NVarChar(50)")]
		public string Vrsta
		{
			get
			{
				return this._Vrsta;
			}
			set
			{
				if ((this._Vrsta != value))
				{
					this.OnVrstaChanging(value);
					this.SendPropertyChanging();
					this._Vrsta = value;
					this.SendPropertyChanged("Vrsta");
					this.OnVrstaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorisnik", DbType="Int")]
		public System.Nullable<int> IdKorisnik
		{
			get
			{
				return this._IdKorisnik;
			}
			set
			{
				if ((this._IdKorisnik != value))
				{
					if (this._Korisnik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKorisnikChanging(value);
					this.SendPropertyChanging();
					this._IdKorisnik = value;
					this.SendPropertyChanged("IdKorisnik");
					this.OnIdKorisnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_ITVideo", Storage="_Korisnik", ThisKey="IdKorisnik", OtherKey="IdKorisnika", IsForeignKey=true)]
		public Korisnik Korisnik
		{
			get
			{
				return this._Korisnik.Entity;
			}
			set
			{
				Korisnik previousValue = this._Korisnik.Entity;
				if (((previousValue != value) 
							|| (this._Korisnik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Korisnik.Entity = null;
						previousValue.ITVideos.Remove(this);
					}
					this._Korisnik.Entity = value;
					if ((value != null))
					{
						value.ITVideos.Add(this);
						this._IdKorisnik = value.IdKorisnika;
					}
					else
					{
						this._IdKorisnik = default(Nullable<int>);
					}
					this.SendPropertyChanged("Korisnik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klijent")]
	public partial class Klijent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKlijenta;
		
		private string _Ime;
		
		private string _Prezime;
		
		private string _BrojTelefona;
		
		private string _Email;
		
		private string _Adresa;
		
		private string _Lozinka;
		
		private string _Status;
		
		private int _IdKorisnika;
		
		private EntityRef<Korisnik> _Korisnik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKlijentaChanging(int value);
    partial void OnIdKlijentaChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnBrojTelefonaChanging(string value);
    partial void OnBrojTelefonaChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnLozinkaChanging(string value);
    partial void OnLozinkaChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnIdKorisnikaChanging(int value);
    partial void OnIdKorisnikaChanged();
    #endregion
		
		public Klijent()
		{
			this._Korisnik = default(EntityRef<Korisnik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKlijenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKlijenta
		{
			get
			{
				return this._IdKlijenta;
			}
			set
			{
				if ((this._IdKlijenta != value))
				{
					this.OnIdKlijentaChanging(value);
					this.SendPropertyChanging();
					this._IdKlijenta = value;
					this.SendPropertyChanged("IdKlijenta");
					this.OnIdKlijentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(50)")]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NVarChar(50)")]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrojTelefona", DbType="NVarChar(20)")]
		public string BrojTelefona
		{
			get
			{
				return this._BrojTelefona;
			}
			set
			{
				if ((this._BrojTelefona != value))
				{
					this.OnBrojTelefonaChanging(value);
					this.SendPropertyChanging();
					this._BrojTelefona = value;
					this.SendPropertyChanged("BrojTelefona");
					this.OnBrojTelefonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="NVarChar(300)")]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lozinka", DbType="NVarChar(20)")]
		public string Lozinka
		{
			get
			{
				return this._Lozinka;
			}
			set
			{
				if ((this._Lozinka != value))
				{
					this.OnLozinkaChanging(value);
					this.SendPropertyChanging();
					this._Lozinka = value;
					this.SendPropertyChanged("Lozinka");
					this.OnLozinkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorisnika", DbType="Int NOT NULL")]
		public int IdKorisnika
		{
			get
			{
				return this._IdKorisnika;
			}
			set
			{
				if ((this._IdKorisnika != value))
				{
					if (this._Korisnik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._IdKorisnika = value;
					this.SendPropertyChanged("IdKorisnika");
					this.OnIdKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_Klijent", Storage="_Korisnik", ThisKey="IdKorisnika", OtherKey="IdKorisnika", IsForeignKey=true)]
		public Korisnik Korisnik
		{
			get
			{
				return this._Korisnik.Entity;
			}
			set
			{
				Korisnik previousValue = this._Korisnik.Entity;
				if (((previousValue != value) 
							|| (this._Korisnik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Korisnik.Entity = null;
						previousValue.Klijents.Remove(this);
					}
					this._Korisnik.Entity = value;
					if ((value != null))
					{
						value.Klijents.Add(this);
						this._IdKorisnika = value.IdKorisnika;
					}
					else
					{
						this._IdKorisnika = default(int);
					}
					this.SendPropertyChanged("Korisnik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Korisnik")]
	public partial class Korisnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKorisnika;
		
		private string _Username;
		
		private string _Ime;
		
		private string _Prezime;
		
		private string _PoslovniEmail;
		
		private string _Lozinka;
		
		private EntitySet<DirektorVideo> _DirektorVideos;
		
		private EntitySet<PravnaVideo> _PravnaVideos;
		
		private EntitySet<EkonomskaVideo> _EkonomskaVideos;
		
		private EntitySet<ITVideo> _ITVideos;
		
		private EntitySet<Klijent> _Klijents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKorisnikaChanging(int value);
    partial void OnIdKorisnikaChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnImeChanging(string value);
    partial void OnImeChanged();
    partial void OnPrezimeChanging(string value);
    partial void OnPrezimeChanged();
    partial void OnPoslovniEmailChanging(string value);
    partial void OnPoslovniEmailChanged();
    partial void OnLozinkaChanging(string value);
    partial void OnLozinkaChanged();
    #endregion
		
		public Korisnik()
		{
			this._DirektorVideos = new EntitySet<DirektorVideo>(new Action<DirektorVideo>(this.attach_DirektorVideos), new Action<DirektorVideo>(this.detach_DirektorVideos));
			this._PravnaVideos = new EntitySet<PravnaVideo>(new Action<PravnaVideo>(this.attach_PravnaVideos), new Action<PravnaVideo>(this.detach_PravnaVideos));
			this._EkonomskaVideos = new EntitySet<EkonomskaVideo>(new Action<EkonomskaVideo>(this.attach_EkonomskaVideos), new Action<EkonomskaVideo>(this.detach_EkonomskaVideos));
			this._ITVideos = new EntitySet<ITVideo>(new Action<ITVideo>(this.attach_ITVideos), new Action<ITVideo>(this.detach_ITVideos));
			this._Klijents = new EntitySet<Klijent>(new Action<Klijent>(this.attach_Klijents), new Action<Klijent>(this.detach_Klijents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKorisnika", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKorisnika
		{
			get
			{
				return this._IdKorisnika;
			}
			set
			{
				if ((this._IdKorisnika != value))
				{
					this.OnIdKorisnikaChanging(value);
					this.SendPropertyChanging();
					this._IdKorisnika = value;
					this.SendPropertyChanged("IdKorisnika");
					this.OnIdKorisnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ime", DbType="NVarChar(50)")]
		public string Ime
		{
			get
			{
				return this._Ime;
			}
			set
			{
				if ((this._Ime != value))
				{
					this.OnImeChanging(value);
					this.SendPropertyChanging();
					this._Ime = value;
					this.SendPropertyChanged("Ime");
					this.OnImeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prezime", DbType="NVarChar(50)")]
		public string Prezime
		{
			get
			{
				return this._Prezime;
			}
			set
			{
				if ((this._Prezime != value))
				{
					this.OnPrezimeChanging(value);
					this.SendPropertyChanging();
					this._Prezime = value;
					this.SendPropertyChanged("Prezime");
					this.OnPrezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoslovniEmail", DbType="NVarChar(50)")]
		public string PoslovniEmail
		{
			get
			{
				return this._PoslovniEmail;
			}
			set
			{
				if ((this._PoslovniEmail != value))
				{
					this.OnPoslovniEmailChanging(value);
					this.SendPropertyChanging();
					this._PoslovniEmail = value;
					this.SendPropertyChanged("PoslovniEmail");
					this.OnPoslovniEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lozinka", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lozinka
		{
			get
			{
				return this._Lozinka;
			}
			set
			{
				if ((this._Lozinka != value))
				{
					this.OnLozinkaChanging(value);
					this.SendPropertyChanging();
					this._Lozinka = value;
					this.SendPropertyChanged("Lozinka");
					this.OnLozinkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_DirektorVideo", Storage="_DirektorVideos", ThisKey="IdKorisnika", OtherKey="IdKorisnika")]
		public EntitySet<DirektorVideo> DirektorVideos
		{
			get
			{
				return this._DirektorVideos;
			}
			set
			{
				this._DirektorVideos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_PravnaVideo", Storage="_PravnaVideos", ThisKey="IdKorisnika", OtherKey="IdKorisnika")]
		public EntitySet<PravnaVideo> PravnaVideos
		{
			get
			{
				return this._PravnaVideos;
			}
			set
			{
				this._PravnaVideos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_EkonomskaVideo", Storage="_EkonomskaVideos", ThisKey="IdKorisnika", OtherKey="IdKorisnika")]
		public EntitySet<EkonomskaVideo> EkonomskaVideos
		{
			get
			{
				return this._EkonomskaVideos;
			}
			set
			{
				this._EkonomskaVideos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_ITVideo", Storage="_ITVideos", ThisKey="IdKorisnika", OtherKey="IdKorisnik")]
		public EntitySet<ITVideo> ITVideos
		{
			get
			{
				return this._ITVideos;
			}
			set
			{
				this._ITVideos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Korisnik_Klijent", Storage="_Klijents", ThisKey="IdKorisnika", OtherKey="IdKorisnika")]
		public EntitySet<Klijent> Klijents
		{
			get
			{
				return this._Klijents;
			}
			set
			{
				this._Klijents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DirektorVideos(DirektorVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = this;
		}
		
		private void detach_DirektorVideos(DirektorVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = null;
		}
		
		private void attach_PravnaVideos(PravnaVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = this;
		}
		
		private void detach_PravnaVideos(PravnaVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = null;
		}
		
		private void attach_EkonomskaVideos(EkonomskaVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = this;
		}
		
		private void detach_EkonomskaVideos(EkonomskaVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = null;
		}
		
		private void attach_ITVideos(ITVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = this;
		}
		
		private void detach_ITVideos(ITVideo entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = null;
		}
		
		private void attach_Klijents(Klijent entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = this;
		}
		
		private void detach_Klijents(Klijent entity)
		{
			this.SendPropertyChanging();
			entity.Korisnik = null;
		}
	}
}
#pragma warning restore 1591
